# Robot.
map_frame_id:                               world
robot_base_frame_id:                        body
robot_pose_with_covariance_topic:           /gt_pose
robot_pose_cache_size:                      50
input_sources:
  point_cloud:
    type:                                   pointcloud
    topic:                                  /cam0/depth/points
    queue_size:                             5
    publish_on_update:                      true
    sensor_processor:
      type:                                 perfect
track_point_frame_id:                       cam
track_point_x:                              0.0
track_point_y:                              0.0
track_point_z:                              0.0
min_update_rate:                            2.0
time_tolerance:                             1.0
time_offset_for_point_cloud:                0.0
sensor_processor/ignore_points_above:       0.4
robot_motion_map_update/covariance_scale:   0.01

# Map
length_in_x:                                1.5
length_in_y:                                1.5
position_x:                                 0.0
position_y:                                 0.0
resolution:                                 0.015  # 1.5 cm
min_variance:                               0.0001
max_variance:                               0.05
mahalanobis_distance_threshold:             2.5
multi_height_noise:                         0.001
surface_normal_positive_axis:               z
fused_map_publishing_rate:                  0.5
enable_visibility_cleanup:                  false
enable_continuous_cleanup:                  false
visibility_cleanup_rate:                    1.0
scanning_duration:                          1.0
num_callback_threads:                       2
postprocessor_pipeline_name:                postprocessor_pipeline
postprocessor_num_threads:                  1

# Init submap
initialize_elevation_map:                   false
initialization_method:                      0
length_in_x_init_submap:                    1.0
length_in_y_init_submap:                    1.0
margin_init_submap:                         0.3
init_submap_height_offset:                  0.01
target_frame_init_submap:                   body
